-- **************************
-- DBS301 - Week 9 Demo
-- Clint MacDonald
-- **************************

-- DML - Data Manipulation Language

-- CRUD
-- Create Read Update Delete

-- INSERT, SELECT, UDPATE, DELETE

-- Creation Scripts
-- covering several parts of DDL (DBDL) Data Definition Language

-- Create tables first with NO foreign Key relationships
-- ROLES
-- DDL
CREATE TABLE zzlstRoles (
    rolename varchar(25) PRIMARY KEY
	);
-- DML
INSERT INTO zzLstRoles (rolename) VALUES ('Actor');
INSERT INTO zzLstRoles (rolename) VALUES ('Actress');
INSERT INTO zzLstRoles (rolename) VALUES ('Director');
INSERT INTO zzLstRoles (rolename) VALUES ('Producer');
INSERT INTO zzLstRoles (rolename) VALUES ('Set Designer');

-- People
CREATE TABLE zzDatPeople (
    personID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name varchar(20) NOT NULL,
    last_name varchar(30) NOT NULL,
    DateOfBirth date,
    City varchar(25) DEFAULT('Los Angeles')
    );
    
-- DML
INSERT INTO zzdatpeople (first_name, last_name, DateOfBirth, City) 
    VALUES ('Clint', 'MacDonald', to_date('19720516', 'yyyymmdd'),'');
INSERT INTO zzdatpeople (first_name, last_name, DateOfBirth, City) 
    VALUES ('Bob', 'McKenzie', to_date('19630812', 'yyyymmdd'),'Great White North');
INSERT INTO zzdatpeople (first_name, last_name, DateOfBirth, City) 
    VALUES ('Doug', 'McKenzie', to_date('19641013', 'yyyymmdd'),' ');  
    
-- DDL Movies
CREATE TABLE zzDatMovies (
    movieID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title varchar(75) NOT NULL,
    production_year int CHECK (production_year BETWEEN 1900 AND 2050),
    budget decimal(15,2) DEFAULT(0.00),
    "length" int);
 
CREATE TABLE zzMovieroles (
    roleID INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    movieID INT,
    personID INT,
    rolename varchar(25));
    
INSERT INTO zzDatMovies (title, production_year, budget, "length")
    VALUES ('Great White North', 1985, 10000, 85);
    
ALTER TABLE zzMovieroles ADD CONSTRAINT fk_roles_movies FOREIGN KEY (movieID) REFERENCES zzDatMovies(movieID);
ALTER TABLE zzMovieroles ADD CONSTRAINT fk_roles_people FOREIGN KEY (personID) REFERENCES zzDatPeople(personID);
ALTER TABLE zzMovieroles ADD CONSTRAINT fk_roles_rolenames FOREIGN KEY (rolename) REFERENCES zzlstRoles(rolename);

-- NOW DML

INSERT INTO zzMovieroles (movieID, personID, rolename)
    VALUES (1, 2, 'Actor');
	
CREATE TABLE tblDatPlayoffGames AS (
    SELECT gameID poGameID, gameNum, hometeam hTeamID, visitteam vTeamID, homescore, visitscore,
        locationid, isplayed, notes
        FROM tblDatGames
        WHERE divid IN (30));
		
ALTER TABLE tblDatPlayoffGames
    ADD CONSTRAINT tblgamepo_pk PRIMARY KEY (poGameID);
    
-- CREATE AS can use fields from multiple tables
 SELECT gameID poGameID, gameNum, h.teamnameshort HomeTeam, v.teamnameshort AwayTeam, homescore, visitscore,
        locationid, isplayed, notes
        FROM tbldatgames JOIN tbldatteams h ON (h.teamid = tbldatgames.hometeam)
          JOIN tbldatteams v ON (v.teamid = tbldatgames.visitteam)
        WHERE divid IN (30);
        
CREATE TABLE tblTEMPdatPOSchedule AS (
    SELECT gameID poGameID, gameNum, h.teamnameshort HomeTeam, v.teamnameshort AwayTeam, homescore, visitscore,
        locationid, isplayed, notes
        FROM tbldatgames JOIN tbldatteams h ON (h.teamid = tbldatgames.hometeam)
          JOIN tbldatteams v ON (v.teamid = tbldatgames.visitteam)
        WHERE divid IN (30)
        );
		
-- CREATION SCRIPTS
-- examples have already been provided 
	-- employee creation script and sportleagues creation scripts

	-- What are the considerations for a creation script?
	